### ISSUE TITLE
[feature]: upload datasets

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/cecilia#12]
Normally, we support .csv file. Please create csv file like:

https://docs.google.com/spreadsheets/d/1sMqSQ8PfYLQcmvQhOa_QxszVZHupI_he9nmNkAsNQzU/edit?usp=sharing

# How to start?

We do not need the huge size of data. Any size of data is welcome. What you need to do is:
*  fork this repo
*  add .csv file to the repo
*  do a PR for it
* give a detail of the dataset with several sentences

# how to use dataset?

Typically, we use dataset to do analysis see https://www.kaggle.com/datasets/skywardai/rmit-semester-1-2024-textbooks/code

Furthermore, we will try to use these data to training the model accroding to the different data type.

**Comment by S3953641** [comment]
https://github.com/SkywardAI/cecilia/pull/13
